[build]
builder="NIXPACKS"
buildCommand="cd server && npm install"

[deploy]
startCommand="cd server && npm start"
rootDirectory="server"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"

[http]
maxBodySize = "50mb"